name: Feature Request
description: Suggest a new feature for Molthub
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe what you'd like and why.
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What use case does it address?
      placeholder: I'm always frustrated when...
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or workarounds you've considered?
  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - Web UI
        - API
        - CLI
        - Fleet Management
        - Security/Policy
        - Observability
        - Other
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context, mockups, or screenshots
